#
# Copyright IBM Corp All Rights Reserved
#
# SPDX-License-Identifier: Apache-2.0
#
version: '3.2'

networks:
  rebnet:
    external:
      name: rebnet 

services:
  ca.switch2logic.co.za:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.switch2logic.co.za
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.hospital1.switch2logic.co.za-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/a9ef47f4b37f2184a9143fa498f79b181608c142d7742836d4320f64ed1291a2_sk
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=rebnet
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/hospital1.switch2logic.co.za/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.switch2logic.co.za
    networks:
      - rebnet
    restart: always  

  orderer.switch2logic.co.za:
    container_name: orderer.switch2logic.co.za
    image: hyperledger/fabric-orderer
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/orderer/msp
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=rebnet
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
    command: orderer
    ports:
      - 7050:7050
    volumes:
        - ./channel-artifacts/:/etc/hyperledger/configtx
        - ./crypto-config/ordererOrganizations/switch2logic.co.za/orderers/orderer.switch2logic.co.za/:/etc/hyperledger/msp/orderer
        - ./crypto-config/peerOrganizations/hospital1.switch2logic.co.za/peers/peer0.hospital1.switch2logic.co.za/:/etc/hyperledger/msp/peerOrg1
    networks:
      - rebnet
    restart: always  

  peer0.hospital1.switch2logic.co.za:
    container_name: peer0.hospital1.switch2logic.co.za
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.hospital1.switch2logic.co.za
      - CORE_LOGGING_PEER=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_LOCALMSPID=Hospital1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_ADDRESS=peer0.hospital1.switch2logic.co.za:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.hospital1.switch2logic.co.za:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer2.hospital1.switch2logic.co.za:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer3.hospital1.switch2logic.co.za:7051     
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.hospital1.switch2logic.co.za:7051
      # # the following setting starts chaincode containers on the same
      # # bridge network as the peers
      # # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=rebnet
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.peer0.hospital1.switch2logic.co.za:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    # command: peer node start --peer-chaincodedev=true
    ports:
      - 7051:7051
      - 7053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/hospital1.switch2logic.co.za/peers/peer0.hospital1.switch2logic.co.za/msp:/etc/hyperledger/msp/peer
        - ./crypto-config/peerOrganizations/hospital1.switch2logic.co.za/users:/etc/hyperledger/msp/users
        - ./channel-artifacts:/etc/hyperledger/configtx
        - ./peer0.hospital1.switch2logic.co.za:/var/hyperledger/production
    depends_on:
      - orderer.switch2logic.co.za
      - couchdb.peer0.hospital1.switch2logic.co.za
    networks:
      - rebnet
    restart: always

  couchdb.peer0.hospital1.switch2logic.co.za:
    container_name: couchdb.peer0.hospital1.switch2logic.co.za
    image: hyperledger/fabric-couchdb
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=rebnet
    ports:
      - 5984:5984
    networks:
      - rebnet
    restart: always 

  peer1.hospital1.switch2logic.co.za:
    container_name: peer1.hospital1.switch2logic.co.za
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer1.hospital1.switch2logic.co.za
      - CORE_LOGGING_PEER=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_LOCALMSPID=Hospital1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_ADDRESS=peer1.hospital1.switch2logic.co.za:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.hospital1.switch2logic.co.za:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer2.hospital1.switch2logic.co.za:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer3.hospital1.switch2logic.co.za:7051       
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.hospital1.switch2logic.co.za:7051
      # # the following setting starts chaincode containers on the same
      # # bridge network as the peers
      # # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=rebnet
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.peer1.hospital1.switch2logic.co.za:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    # command: peer node start --peer-chaincodedev=true
    ports:
      - 8051:7051
      - 8053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/hospital1.switch2logic.co.za/peers/peer1.hospital1.switch2logic.co.za/msp:/etc/hyperledger/msp/peer
        - ./crypto-config/peerOrganizations/hospital1.switch2logic.co.za/users:/etc/hyperledger/msp/users
        - ./channel-artifacts:/etc/hyperledger/configtx
        - ./peer1.hospital1.switch2logic.co.za:/var/hyperledger/production
    depends_on:
      - orderer.switch2logic.co.za
      - couchdb.peer1.hospital1.switch2logic.co.za
    networks:
      - rebnet
    restart: always 

  couchdb.peer1.hospital1.switch2logic.co.za:
    container_name: couchdb.peer1.hospital1.switch2logic.co.za
    image: hyperledger/fabric-couchdb
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=rebnet
    ports:
      - 6984:5984
    networks:
      - rebnet
    restart: always  

  
  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.hospital1.switch2logic.co.za:7051
      - CORE_PEER_LOCALMSPID=Hospital1MSP
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/hospital1.switch2logic.co.za/users/Admin@hospital1.switch2logic.co.za/msp
      - CORE_CHAINCODE_KEEPALIVE=10
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=rebnet
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/hospital1.switch2logic.co.za/peers/peer0.hospital1.switch2logic.co.za/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/hospital1.switch2logic.co.za/peers/peer0.hospital1.switch2logic.co.za/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/hospital1.switch2logic.co.za/peers/peer0.hospital1.switch2logic.co.za/tls/ca.crt
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    networks:
        - rebnet
    restart: always     
