#
# Copyright IBM Corp All Rights Reserved
#
# SPDX-License-Identifier: Apache-2.0
#
version: '3.4'

networks:
  rebnet:
    external: true

services:

  peer2.hospital1.switch2logic.co.za:
    container_name: peer2.hospital1.switch2logic.co.za
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer2.hospital1.switch2logic.co.za
      - CORE_LOGGING_PEER=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_LOCALMSPID=Hospital1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_ADDRESS=peer2.hospital1.switch2logic.co.za:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.hospital1.switch2logic.co.za:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.hospital1.switch2logic.co.za:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer3.hospital1.switch2logic.co.za:7051       
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2.hospital1.switch2logic.co.za:7051
      # # the following setting starts chaincode containers on the same
      # # bridge network as the peers
      # # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=rebnet
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.peer2.hospital1.switch2logic.co.za:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    # command: peer node start --peer-chaincodedev=true
    ports:
      - 9051:7051
      - 9053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/hospital1.switch2logic.co.za/peers/peer2.hospital1.switch2logic.co.za/msp:/etc/hyperledger/msp/peer
        - ./crypto-config/peerOrganizations/hospital1.switch2logic.co.za/users:/etc/hyperledger/msp/users
        - ./channel-artifacts:/etc/hyperledger/configtx
    depends_on:
      - couchdb.peer2.hospital1.switch2logic.co.za
    networks:
      - rebnet
    restart: always  

  couchdb.peer2.hospital1.switch2logic.co.za:
    container_name: couchdb.peer2.hospital2.switch2logic.co.za
    image: hyperledger/fabric-couchdb
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=rebnet
    ports:
      - 7984:5984
    networks:
      - rebnet
    restart: always 


  peer3.hospital1.switch2logic.co.za:
    container_name: peer3.hospital1.switch2logic.co.za
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer3.hospital1.switch2logic.co.za
      - CORE_LOGGING_PEER=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_LOCALMSPID=Hospital1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_ADDRESS=peer3.hospital1.switch2logic.co.za:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.hospital1.switch2logic.co.za:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer2.hospital1.switch2logic.co.za:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.hospital1.switch2logic.co.za:7051       
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer3.hospital1.switch2logic.co.za:7051
      # # the following setting starts chaincode containers on the same
      # # bridge network as the peers
      # # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=rebnet
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.peer3.hospital1.switch2logic.co.za:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    # command: peer node start --peer-chaincodedev=true
    ports:
      - 10051:7051
      - 10053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/hospital1.switch2logic.co.za/peers/peer3.hospital1.switch2logic.co.za/msp:/etc/hyperledger/msp/peer
        - ./crypto-config/peerOrganizations/hospital1.switch2logic.co.za/users:/etc/hyperledger/msp/users
        - ./channel-artifacts:/etc/hyperledger/configtx
    depends_on:
      - couchdb.peer3.hospital1.switch2logic.co.za
    networks:
      - rebnet
    restart: always 

  couchdb.peer3.hospital1.switch2logic.co.za:
    container_name: couchdb.peer3.hospital2.switch2logic.co.za
    image: hyperledger/fabric-couchdb
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=rebnet
    ports:
      - 8984:5984
    networks:
      - rebnet 
    restart: always     

